server:
  port: 9201
info:
  component: Config Service
endpoints:
  restart:
    enabled: true
spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Even521/spring-cloud-demo.git
          search-paths: spring-cloud-config-repo
          #ignoreLocalSshSettings: true
          #hostKey: someHostKey
          #hostKeyAlgorithm: ssh-rsa
          privateKey: ｜

      label: master


