server:
  port: 9201
info:
  component: Config Service
endpoints:
  restart:
    enabled: true
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Even521/spring-cloud-demo.git
          search-paths: spring-cloud-config-repo
      label: master


