server:
  port: 9299
logging:
  level:
    org.springframework.cloud.gateway: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:9200/eureka/
filters:
  -name: Hystrix
  args:
    name: default
    fallbackUri: 'forward:/defaultfallback'
# hystrix 信号量隔离，3秒后自动超时
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
  shareSecurityContext: true
spring:
  cloud:
    gateway:
      routes:
        - id: admin
          uri: http://127.0.0.1:9203
          predicates:
            - Path=/admin/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10  # 令牌桶的容积
                redis-rate-limiter.burstCapacity: 3  # 流速 每秒
                key-resolver: "#{@hostAddrKeyResolver}" #SPEL表达式去的对应的bean
      redis:
        host: 192.168.0.178
        password: 123456
        port: 6379
        database: 1


