server:
  port: 9299
logging:
  level:
    org.springframework.cloud.gateway: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:9200/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: baidu
          uri: http://www.baidu.com
          predicates:
            - Path=/baidu
        - id:

